### ISSUE TITLE
Missing links and dead sites

### ISSUE THREAD

**Issue by joshavanier** [XXIIVV/Webring#109]
I looked through the current webring links and found the following issues:
- theiceshelf.com (dead site) - I can't find the name of the original owner so please tag them if you know them
- @simbolo (dead site)
- ~~@cblgh (missing webring link)~~
- ~~@jda0 (missing webring link)~~

Please update your sites as soon as possible. I will temporarily comment out the dead sites just to keep the webring working. Just submit a pull request when it's ready. Thank you :)

**Comment by cblgh** [comment]
@joshavanier not sure why my site is greyed out, but cblgh.org works and links correctly

**Comment by joshavanier** [comment]
@cblgh Oh that's just the CSS styling for visited links. Where's the webring link on your site?

**Comment by cblgh** [comment]
ahhh, i completely missed the part where that was a requirement. i'll fix it today :)

**Comment by jda0** [comment]
@joshavanier the webrink link is under networks on the far left. The link is clearer on the redesigned version I’ll be pushing today.
