### ISSUE TITLE
Site is giving a 401

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#119]
blog.lucasdidthis.com is prompting for a username/password and therefore giving a 401. Not sure how to contact this person to see if it's intentional or not. Do we have a way of going about this before removing a dead link from the webring?

**Comment by joshavanier** [comment]
Pinging @lucasdidthis

**Comment by ckipp01** [comment]
Also, this morning I played around with this a bit: https://webring-checker.now.sh

I plan on cleaning it up and adding some more information to it, but if we want, we can get a read on the health of the ring by hitting this. For now it will just give each site name and the status of their site.

**Comment by ckipp01** [comment]
Pinging @MoreThanLuck I believe I remember seeing that you changed your url. Is https://ianjbattaglia.co no more?

**Comment by lucasdidthis** [comment]
Sorry, blog.lucasdidthis.com is going to be back on sunday (at the latest). Had some maintenance/relocation hustle when changing stuff...

**Comment by lucasdidthis** [comment]
blog.lucasdidthis.com is back online! It's still pretty much a work in progress, but at least you can see _something_ and read previous posts. ;-) I changed the URL to the main domain (lucasdidthis.com), but there's a redirect for the old subdomain, so there should be no errors anymore.

**Comment by neauoire** [comment]
Thanks :)

**Comment by MoreThanLuck** [comment]
@ckipp01 Back online! Thanks for the heads up.
