### ISSUE TITLE
Some posts aren't showing up, despite being pulled and parsed

### ISSUE THREAD

**Issue by Bradshaw** [XXIIVV/Webring#160]
Currently there are some posts that aren't appearing in the feed, but will appear when certain filters are applied

To see this, select the #tag or #cory tags, the messages visible there don't appear when there's no filter

I don't currently have any theory or clues as to why this is happening

**Comment by ckipp01** [comment]
@Bradshaw it looks like the hallway only shows I _think_ the 50 newest one? Where as the posts that are in #tag or #cory are from 3 days ago, so they are simply too old and now shown in the feed?

**Comment by Bradshaw** [comment]
@ckipp01 🤦‍♂️

Yeah, that's what's happening

I figured there was a bug because I wasn't seeing the _same_ missing posts as the live version, but because my test version couldn't pull certain feeds due to cross-origin policies, it's just that the cutoff point is further back in time...
