### ISSUE TITLE
Implement twtxt native mentions support

### ISSUE THREAD

**Issue by neauoire** [XXIIVV/Webring#171]
Halp @Bradshaw

**Comment by kodedninja** [comment]
Is there some progress on this one?

**Comment by neauoire** [comment]
No news from gaeel, so I don't think so, wanna try to tackle that one?

**Comment by kodedninja** [comment]
Might have a look at it tomorrow, because it's quite annoying. But no guarantees, I'm not a native regexp speaker.

**Comment by ckipp01** [comment]
Are we wanting to support the current @mention and the twtxt native support, or just only use the native option?

**Comment by neauoire** [comment]
Just the twtxt native, we could make up our own quick mention if we wanted like `^ckipp`

**Comment by kodedninja** [comment]
Ah, so we only want the native. I thought we keep them both. But I actually prefer the native, it enhances discovery. So 👍

**Comment by ckipp01** [comment]
#190 fixes this.

**Comment by kodedninja** [comment]
Great job @ckipp01!
