### ISSUE TITLE
Discussion on criteria of being in the webring

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#179]
I guess this is just a question, but I've wondered a couple times if there is any criteria on what should or should not be in the webring. We do explicitly say:
> Single page websites, and websites acting only as portals to other social platforms, will be rejected.

and we also mention that wiki's,diaries, blogs, etc are welcome, but do we want to be a bit more explicit on what is actually included? What if someone has a site with like extreme violence or something on there. I know as part of the webring I'd be a bit iffy on someone navigating from my site to that. Should we potentially be a bit more specific on the _type_ of blog, wiki, etc that we'd like to be part of the webring, or keep it wide open?

**Comment by kodedninja** [comment]
I also wanted to open an issue like this when I became a moderator. I think we definitely need it, the same way as Merveilles.town has its own rules where we can point to if something's not right, without any personal opinion involved.

**Comment by neauoire** [comment]
I agree.

So far I've been going by feel, and message. In terms of topics, I'm thinking if someone has found its way to the webring's repository and has the knowledge to actually make a PR with their own website, then that means this person has walked part of the way.

I general, **No violent content, no racism, sexism or speciesism**. I usually do the rounds once every few days, I check what people have been up to, and I think I have each RSS feed into my reader, giving me a bit of an overview. I have not yet found something that made me think someone has violated this.

There was [this PR](https://github.com/XXIIVV/Webring/pull/87) which linked to an incredibly deep website, which I could not be sure it didn't have some kind of potential bad message, so I have not yet merged it. I noticed there were some religious topics and I kind of hold off. 

There are some sites that had a blog or a wiki at some point and reverted to a single pager, which I want to remove from the ring, but I would like to get in touch with the person before.

**Comment by ckipp01** [comment]
I know what you mean about the PR you mentioned @neauoire, and that's sort of a hard one to gauge. One other related thing, which you touched on, is if a site reverted back to a single page, should we just reach out to the person to potentially see if they have another site they'd possibly like to link to, and if not, remove it from the webring in violation of the no single page rule?

Sort of similar, what if a site goes down? For example there has been a site giving a 503 almost the past week? I sort of feel at the week mark we should reach out and see if they are just doing maintenance or something. If there isn't a response, it may be best to remove it after a week or so in order to not have a dead link in the chain.

**Comment by neauoire** [comment]
We should open an isse and tag that person if we don't have their email, if they don't answer, we remove it yeah.

**Comment by ckipp01** [comment]
Sounds good. I'll close this for now. If need be, we can revisit this in the future.

**Comment by ckipp01** [comment]
Already revisiting this since I have a question for the both of you (@neauoire  @kodedninja ) which #186 brings up. How do we want to approach sites that are selling services? I know for myself, I really don't want to be browsing the webring and trying to be sold something.

One other question. How do we feel about trackers on sites?

**Comment by kodedninja** [comment]
@ckipp01 services are one point, but I would generally try to keep the sites somehow connected (in topic, in style, etc.), which doesn't mean that we should refuse all that are different, but at least keep the transformation natural (by accepting more sites with small differences, even a bigger difference will feel natural over time). This way we can also keep the direction in which the Webring's going in hands.

**About trackers:** of course, I hate them, but I do understand that some people do like them. So instead of not letting tracked sites into the ring, I would go with "the Webring prefers non-tracked sites". Owners would have to note if the site is tracked and this would be visible in the list. And also, I would exclude them from the random site redirect.

This would encourage owners to remove the trackers, while still keeping the Webring open for them.

**Comment by ckipp01** [comment]
@kodedninja Again, I agree with what you're saying. I'm just sort of scratching my head over how exactly to enforce that. For example, @neauoire mentioned #87, which in my opinion falls in line with what you're saying. I don't feel like it fits the webring. I really want to come up with some type of way to make that judgement call rather than it being just a gut reaction. I'm going to assume the way any of the maintainers may approach that call may be a bit different, so it'll be helpful to have something more concrete.

I agree with making a note about "the Webring prefers non-tracked sites". As for the noting it in the sites.js file, I don't know how I feel about that. I'll defer to @neauoire

**Comment by neauoire** [comment]
Good call on the business site PR, that would have been a no for me. The website is **a place for personal websites**, this found itself too far in the impersonal range of the spectrum.

Actually, I like the idea of not allowing tracked websites, I mean, we have the opportunity here to try and stear toward our "ideal web", let's not make any concessions. Tracked websites cannot be part of the webring. Do you use [Firefox Lightbeam](https://addons.mozilla.org/en-US/firefox/addon/lightbeam/) for that?

**Comment by ckipp01** [comment]
I use a combination of [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) and [Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) to block and see what third party calls are being made (Chromium is my main browser). I just did a sort of informal check, and there is actually more sites than I thought that are using tracking. For example in the first 30 sites of the webring there is at least 6 that have google analytics. So if we are going to enforce that type of rule, we'll have to figure out how we approach that. Do we just enforce it moving forward?
