### ISSUE TITLE
Parsing twtxt files with comments

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#183]
I noticed that the newest feed to the webring isn't coming through in the hallway. It looks like it's due to comments being at the top of the file. Since we didn't account for that in the parsing, not working right. It should be an easy fix to just remove any lines that are comments. 

Example:
https://lublin.se/twtxt.txt

**Comment by neauoire** [comment]
Could you pull and see if that fixes it on your end?

**Comment by ckipp01** [comment]
Yup, that does the trick!
