### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#191]
Hey @serocell, it looks like there is a CORS issue with your hosting of your twtxt file. Currently your posts aren't showing up in the hallway because of it. You can find an [example in the readme](https://github.com/XXIIVV/Webring/blob/master/README.md) if you don't know how to fix this.

**Comment by serocell** [comment]
all fixed, sorry about that.

**Comment by ckipp01** [comment]
Sweet, looks good! Thanks!
