### ISSUE TITLE
Single page website

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#192]
Hey @hubret! Just checking in since we noticed that your current linked site on the webring is just single page site, which is against the rules of the webring as seen in the readme. Do you by chance have another site with more stuff on it that you'd want to link, or are you in the process of expanding your current site? We're trying to keep the webring in line with what it's intended to be, a collection of wikis, diaries, portfolios and the like, so if you're site isn't really active anymore, and seeing that it's currently just a single page, we plan on removing it.

**Comment by hubret** [comment]
In the process of adding, it looks like this because I scrapped my old wiki.

**Comment by ckipp01** [comment]
Sounds good. I'll leave the issue open for now and check back in a week or so. If nothing has changed it may be best to remove your site for now, and then have you send in a pr when you have it ready for prime time.

**Comment by ckipp01** [comment]
Hey @hubret! I went ahead and removed your site from the webring today. However, as soon as you get it updated, please send it a pr to get it back added!
