### ISSUE TITLE
No webring logo and copy of tumblr

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#194]
Hey @streeetlamp! Just wanted to reach out about your site now in the webring. We're currently doing a check through all the sites and noticed your site wasn't really in line with multiple of our rules. If we understand it correctly, it's just a portal to your tumblr since it seems to just be posting from your tumblr. Secondly, there is no webring logo. Also, you have a lot of trackers/adds going on in your site, which isn't really in line with the values of the webring.

I'll leave this up for a few days before removing the site just in case you're currently moving some things around or want to replace this site with another you may have.

**Comment by neauoire** [comment]
Actually, this is an instant removal from me, no link-back websites don't get a week's time to correct.

**Comment by streeetlamp** [comment]
Hi, very sorry for missing this notification. I have updated my site and submitted a PR. Please let me know if I have made any mistakes or overlooked something. Thanks
