### ISSUE TITLE
Fix styling in the hallway

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#198]
![image](https://user-images.githubusercontent.com/13974112/61689204-0aeaca80-ad27-11e9-9d1b-babdf17dbed2.png)
If you look at the image, since there is such a long list of tags, it actually extends further than the feed list when on a wide monitor.

**Comment by neauoire** [comment]
Maybe we should trip at the 10 most popular, of each category.

**Comment by ckipp01** [comment]
Yea, that's much better :+1:
