### ISSUE TITLE
Broken link in the ring

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#199]
@MoreThanLuck hey Ian! I noticed your site has been 404ing the past few days. Are you just doing some work on it? Just want to make sure in order to not have a broken link in the ring.

**Comment by MoreThanLuck** [comment]
Yes, sorry! https://IanJBattaglia.co is down right now, taken offline while I do a refresh. Hope to have it back up asap.

**Comment by ckipp01** [comment]
No worries! I'll leave this open for now and check back in after a while.

**Comment by MoreThanLuck** [comment]
Thanks. I actually remade it with Hugo and have it how I like it running locally, but ran into issues with adding the repo and deploying on netlify. I'm still an amateur dev, haha. Should only be a few days until I figure it out.

**Comment by ckipp01** [comment]
No worries at all! If you get stuck and there is anything we can do to help, I'm sure any of us would be happy to.

I'm sure you've already looked, _but_ just in case you didn't see this, there looks to be a guide on deploying hugo sites to netfliy.

https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

Again, after a few days, if you are still struggling, let us know!

**Comment by MoreThanLuck** [comment]
Thanks Chris. I'm aware of this guide, but might benefit from going through and reading it more closely. I'll try some more troubleshooting on my own, but might end up reaching out if I can't figure it out. Thanks!

**Comment by ckipp01** [comment]
@MoreThanLuck 
Hey Ian, you making any headway, or need any help?

**Comment by ckipp01** [comment]
Hey @MoreThanLuck just giving you a heads up that I removed your site from the webring in order to not have a broken link in the chain. As soon as you get your site up and deployed, please send in a PR to get up back up!

Also if you do end up needing any help with getting in deployed, don't hesitate to reach out.

**Comment by MoreThanLuck** [comment]
@ckipp01 Got it, thanks. Honestly, I just haven't had time to look at it yet. I think I should be able to try and troubleshoot this Sunday, but may ask for help beyond that.

**Comment by MoreThanLuck** [comment]
Hey, sorry I've taken so long on this. I do think I need help. Anyone familiar with Hugo sites? Is this a decent place to post a question? (If not, I'll move it.)

This is my second Hugo site. I remade my portfolio website with Hugo using the [Strata theme, repo here](https://github.com/digitalcraftsman/hugo-strata-theme). Like with the first Hugo site I did, I developed it while running Hugo server to make sure it worked as intended. I finished it, and it looks great on my local machine. Then, I ran the Hugo command to initialize the site, did `git init` and added it all to a [repo](https://github.com/MoreThanLuck/portfolio), which I pushed to Netlify. For some reason, it's only rendering raw HTML, as if the site isn't building correctly. Any ideas?

**Comment by joshavanier** [comment]
I think @setphen uses Hugo and might be able to help you with that :)

**Comment by MoreThanLuck** [comment]
Thank you! Hope you can, Stephen. If it helps, I'm happy to send you a zip with the full website directory, as well as a link to the current Netlify deploy and their deploy log (which admittedly isn't very helpful).

The repo that got made doesn't match the directory on my local machine, but I don't have a gitignore hidden or anything. Wonder if the file structure is part of the problem? Or the theme choice?

**Comment by ckipp01** [comment]
Total assumption, but I'd guess that the theme choice probably isn't the issue.

What is exactly happening? Also, what ends up being different from the directory locally than your directory on your git repo?

**Comment by MoreThanLuck** [comment]
Yeah, it seems unlikely, but it doesn't seem like it's been maintained in a while, even though the creator is a Hugo maintainer. 

There's a few empty directories that don't make it up. Wonder if the difference in file structure if throwing it off? It seems like the site just isn't building any of the Go, JS, CSS etc. On my local box through `hugo server`, the site looks as intended with the sidebar, links, etc. But the Netlify deploy is just raw HTML + CSS. A little more brutalist than I was going for!

I can add screenshots this evening.

**Comment by setphen** [comment]
hey @MoreThanLuck :)

I haven't used Netlify before, but can you tell me what your configuration file looks like? If the site isn't getting built when you deploy, my first guess would be that it's encountering an error when trying to run Hugo.

Did you follow this guide? https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

**Comment by MoreThanLuck** [comment]
Thanks Stephen. I thought I did, but maybe I skipped a basic step. I got one site to work exactly as intended, so I'm not sure where I went astray with this one. 

Here's my [config.toml](https://github.com/MoreThanLuck/portfolio/blob/master/config.toml). Is the flaw in not specifying Hugo version?

**Comment by setphen** [comment]
@MoreThanLuck Sorry, I meant the netlify configuration file, `netlify.toml`. Also, if you can share the netlify log output, maybe that has a clue.
