### ISSUE TITLE
twtxt feed for http://xxiii.co/twtxt.txt

### ISSUE THREAD

**Issue by neauoire** [XXIIVV/Webring#203]
**Name of the site:** http://xxiii.co/twtxt.txt
Blocked loading mixed active content “http://xxiii.co/twtxt.txt”

cc @serocell

**Comment by serocell** [comment]
that was updated to https://xxiii.co/twtxt.txt <http://xxiii.co/twtxt.txt> has
it perhaps been reverted by a pull request that predated that update?

**Comment by neauoire** [comment]
It's very possible, let me add it again as https.

**Comment by serocell** [comment]
would I be best to do another pull request to resolve this?

**Comment by neauoire** [comment]
No no :)

**Comment by serocell** [comment]
ok great.

**Comment by serocell** [comment]
thanks.

**Comment by neauoire** [comment]
Okay that fixed it, sorry about that!
