### ISSUE TITLE
Incorrect twtxt format

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#229]
Hey @VegaDeftwing, I just looked at your twtxt feed to figure out why it wasn't parsing correctly, and it looks like you're not separating your timestamp and message by a tab but by a single space. This is causing it not to parse right.

You can see more details about the formatting here on the [twtxt site](https://twtxt.readthedocs.io/en/stable/user/twtxtfile.html) or on the [readme](https://github.com/XXIIVV/Webring#joining-the-hallway).

**Comment by VegaDeftwing** [comment]
Wow, not sure how I managed to overlook that. It's been fixed

**Comment by ckipp01** [comment]
Looks good!
