### ISSUE TITLE
Fix duplicates in the wiki

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#234]
It looks like when an author has the same word it combines the word and shows both definitions, but it actually does that for each time it comes across it causing the duplicated words to be displayed twice.

![image](https://user-images.githubusercontent.com/13974112/62415353-dcbf9180-b628-11e9-8463-45d458609907.png)

**Comment by dym-sh** [comment]
imo, to properly fix this issue and make other data-manipulation based operations much simpler, it will take a complete overhaul of current codebase

constant html-string concatenation in the middle of composing the page makes it quite difficult contribute to
instead, any kind of templating would be very much preferred
i would recommend looking at https://svelte.dev or https://choo.io for example

unless reinventing the bicycle is exactly the point.

**Comment by ckipp01** [comment]
So, I guess there are multiple points to address from your comment, @dym-sh.

I think it's safe to assume @neauoire doesn't want to adopt an external framework for the webring. While both are great tools, Svelte would introduce a build phase, which we don't want. We like the idea of being able to download the source and have it run exactly the same locally when we open in our browser as it does live. imo, this project is small enough that introducing something like Svelte would be more work than benefit. But again, I won't speak for @neauoire on that, it's just my assumption.

Choo would be a better option than Svelte for this, but this project is small and simple enough that we'd basically just be utilizing a bit of the state tools and the choo/html which basically is just string interpolation. So my opinion on that is that it's probably not worth it.

I do understand what you mean, it does take a bit to get used to the coding style that the webring has, specifically meaning the constructor function pattern. I _do_ think we can clean it up a bit, and I'm actually working on a branch now that I believe will make working with the wiki much easier, port all three views over to more semantic html, and reduce a lot of the css.

Finally, especially the wiki and hallway are still relatively young, and as time goes on they will mature and change. If you have ideas to clean them up, by all means send a pr.

**Comment by dym-sh** [comment]
well, yes, adding external library is not the best way to keep it "indie", but composing html should be the final step

**Comment by neauoire** [comment]
hell no, we keep it simple and stupid.
