### ISSUE TITLE
Don't cut off categories mid word

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#241]
![image](https://user-images.githubusercontent.com/13974112/62488956-d4508d80-b7c5-11e9-925a-c90251c0b0a7.png)

We should probably get a better way to do this. Either change the way the sidebar is done to better accomodate longer phrases, or cut off at a full word or at least have a ... to end a word or something so it doesn't just stop at the end of a word.

**Comment by joshavanier** [comment]
Just set a max-width value and `text-overflow: ellipsis;`
