### ISSUE TITLE
[Convo] Displaying categories in wiki.

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#243]
Couple questions on how we want to do this as we continue to get more stuff. I noticed that all the categories are sort of just merged. It may be just me, but it's annoyed me a bit that they aren't alphabetically ordered. Thoughts?

Another thing is that we currently don't display categories if they are under 5 entries in that category. I'm assuming it was designed that way to not have a ton of entries in the sidebar, but I'm curious if there is a different way to do it that still allows for someone to search for a category or go to a category that may have under 5.

@neauoire would you be open to an idea where the homepage of the wiki is a listing of all categories available? Then once you select one the sidebar appears?

**Comment by neauoire** [comment]
Maybe the sidebar is just not a good idea for this view? 

We could turn the sidebar into a kind of footer, that is always visible under the content, so if you're reading one term, then you see:

- The term's definition
- The term's related category terms
- The list of categories

**Comment by ckipp01** [comment]
So I think I'm going to close this for now. I'm actually pretty satisfied with how this is working now. If we need to revisit this, we can open it back up.
