### ISSUE TITLE
Fix top level lists

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#244]
Currently if the category just contains a list of items, it shows their index like so:

![image](https://user-images.githubusercontent.com/13974112/62492122-fcdc8580-b7cd-11e9-9f57-f9455169376e.png)

The numbering really isn't adding anything so I'd recommend just removing it.

**Comment by neauoire** [comment]
yes! no keys for arrays, I remember seeing this and I thought, weird, why would they just use numbers as keys.. I didn't realize that it was an array.
