### ISSUE TITLE
Minimal navigation

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#265]
There has been enough times now where I'm in the wiki and want to go back to the main page or peek in the hallway that it'd be nice to have some sort of non-intrusive minimal navigation to be able to move around the various views of the webring.

**Comment by neauoire** [comment]
We could make this footer standard for all projects.

<img width="782" alt="Screen Shot 2019-08-11 at 7 53 52 PM" src="https://user-images.githubusercontent.com/1455726/62832952-bd9cb180-bc71-11e9-9363-1318e8f8b6a6.png">
