### ISSUE TITLE
Vega's feed not being displayed

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#268]
**Please describe the issue in the hallway:**

It looks like vega's feed isn't being displayed on the hallway, and there also isn't a console error which is weird. I just noticed this because I see his message when I view it with the webring-cli
![image](https://user-images.githubusercontent.com/13974112/62838500-6e5c7e00-bc7d-11e9-8a9e-68d6eb1d8aaa.png)

but I don't see it on the web

![image](https://user-images.githubusercontent.com/13974112/62838508-8207e480-bc7d-11e9-8575-6c30551a2ac4.png)

and there isn't an error in the console that is tied to it

![image](https://user-images.githubusercontent.com/13974112/62838520-a2d03a00-bc7d-11e9-868d-91b08c931c58.png)

**Comment by neauoire** [comment]
cc @VegaDeftwing

**Comment by VegaDeftwing** [comment]
ヽ（´ー｀）┌ I'm curious why the date is showing up as NaN days too, unless I formatted the date wrong, but it looks right to me.

**Comment by ckipp01** [comment]
So it looks like it's not a valid timestamp. You can quickly tell by trying to create a new date from it like so:
![image](https://user-images.githubusercontent.com/13974112/62845828-8eb32980-bccb-11e9-95cc-ea2c5abeadd3.png)

What are you using to create the timestamp?

**Comment by VegaDeftwing** [comment]
That one was manually entered so I could set things up. .-.

**Comment by ckipp01** [comment]
haha, no worries. If you don't want to use the twtxt client, you can also just make a short script to do it. For example, @joshavanier has a shell script here https://merveilles.town/@joshavanier/102506548430731283 or you can see how I create on in JS [here](https://github.com/ckipp01/webring-cli/blob/master/commands/hallway-write.js#L24) in the webring-cli.

If you can, just delete your first entry and try it again, and hopefully it should work fine!

**Comment by VegaDeftwing** [comment]
Alright. Ill give it a go tomorrow, its already midnight here. Sorry for
all the trouble

**Comment by ckipp01** [comment]
No trouble at all. :+1:

**Comment by VegaDeftwing** [comment]
I think I fixed it?

**Comment by ckipp01** [comment]
Indeed. Looks good!

**Comment by VegaDeftwing** [comment]
![DeepinScreenshot_select-area_20190816153055](https://user-images.githubusercontent.com/11283620/63196460-f904fa80-c03a-11e9-8c21-4d37438fa16f.png)

Looks like you can see me @ckipp01 , but I don't see me!

**Comment by ckipp01** [comment]
![image](https://user-images.githubusercontent.com/13974112/63208246-fc979080-c0d1-11e9-9558-d9d989c291ff.png)

Weird, I'm seeing you. Are you able to open your console and tell me if you see any warnings/errors?

**Comment by VegaDeftwing** [comment]
![DeepinScreenshot_select-area_20190817041156](https://user-images.githubusercontent.com/11283620/63209353-37cf9a80-c0a5-11e9-801b-5e851f5b6738.png)

odd. I'll play around with it soon-ish and see if I can figure out what's going on.

**Comment by VegaDeftwing** [comment]
Ughh. one of the adblockers I have installed in Vivaldi decided my site was bad. ヽ(　￣д￣;)ノ
Clearly a non-issue normally, but worth noting if anyone else notices the same

**Comment by ckipp01** [comment]
Ahh, well I'm glad you figured it out, ha. I'll keep that in mind in case it happens to someone else as well.
