### ISSUE TITLE
[Indental] Allow indented comments

### ISSUE THREAD

**Issue by ljcooke** [XXIIVV/Webring#281]
**Please describe the issue in the wiki:**
Indental does not support indented comments.

Example:

```
TEST 1
  ; indented comment
  KEY : VALUE

TEST 2
; no indent
  KEY : VALUE
```

For `#TEST 1` this shows the comment on the wiki (and not the data):

> ; indented comment
> \- @……

For `#TEST 2` this produces the expected output:

> **key**
> VALUE - @……

**Comment by neauoire** [comment]
thanks I'll fix that.

**Comment by ckipp01** [comment]
@ljcooke I was actually just looking at this and was going to fix it, but I actually can't reproduce it.

For example I have 
```
DICTIONARY
  ; testing
  Ennui : A feeling of weariness and dissatisfaction.
  Pariah : One that is despised or rejected.
```
and it seems to do exactly as expected, skip the indented `; testing` and then display both Ennui and Pariah. Am I misunderstanding what you mean?
