### ISSUE TITLE
tomupon CORS issue

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#285]
**Please describe the issue in the wiki:**

![image](https://user-images.githubusercontent.com/13974112/63010926-991a2280-be87-11e9-8e33-3abbd2f9d445.png)

@et0and do you need any help getting this fixed?

**Comment by et0and** [comment]
Hi Chris, I think I have just managed to fixed this by enabling headers via a netlify.toml file. I have tried checking this with web console on my browser and it appears to be okay, but could you please let me know if this is still an issue?

**Comment by ckipp01** [comment]
Hey! Looks like that did the trick!
