### ISSUE TITLE
TateCarson is 404ing

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#286]
**Name of the site:**
https://www.tatecarson.com/
Hey @tatecarson I've noticed your site has been 404ing the past few days.

**Comment by tatecarson** [comment]
I've been experimenting with [ipfs](https://ipfs.io/) and for some reason it's not working in Brave, but is working fine in Chrome. I will look into it.

**Comment by ckipp01** [comment]
Sounds good. I'm in Chromium btw, and it's 404ing for me as well, so I don't think it's working in Chrome.

**Comment by joshavanier** [comment]
I'm on Firefox and it's still a 404

**Comment by tatecarson** [comment]
Fixed the DNS, should be all good now.

**Comment by ckipp01** [comment]
Looks to be working. Thanks!
