### ISSUE TITLE
Prettier urls, #celest+navi instead of #CELEST%20NAVI

### ISSUE THREAD

**Issue by neauoire** [XXIIVV/Webring#292]
**Please describe the issue in the wiki:**

**Comment by ckipp01** [comment]
I know this is merged now, so I was going to close this, but thinking about it again, the way this is implemented now blocks someone from using  + in the category name. If they do, it will break. That was one of the benefits of encoding the URI, was not having to worry about that.

Do you think this matters even? Should we use ++ instead just to make a bit more unique?

¯\_(ツ)_/¯

If you think it's fine though, then this can just be closed.

**Comment by neauoire** [comment]
It doesn't matter, people shouldn't use `+` in their category names in the first place.

**Comment by ckipp01** [comment]
Sounds good :+1:
