### ISSUE TITLE
https://gndclouds.cc is a 404

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#300]
**Name of the site:**
https://gndclouds.cc

It looks like the site is redirecting to https://gndclouds.github.io/gndclouds.cc/, which is a 404. However, it looks like gndclouds.github.io is working.

@gndclouds, hey! Are you able to update your entry in the webring to fix this?

**Comment by gndclouds** [comment]
I migrated my domain to Zeit and looks like there was a path error when importing the CNAME record. Its all fixed not. Thanks, @ckipp01 for the catch.

**Comment by ckipp01** [comment]
No problem!
