### ISSUE TITLE
neufv.systems

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#302]
Hey @nuel! I just came across your page, and users are getting a warning since your ssl certificate doesn't match your current domain. Also, your site is currently just a single page, which goes against the webring rules.

Are you just in the process of updating some things?

**Comment by dym-sh** [comment]
i think he moved that to https://nuel.work

**Comment by nuel** [comment]
i did, i'm sorry, i'll remove my entry. also @dym-sh, they/them please
