### ISSUE TITLE
Check nested parsing

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/webring#326]
Referring back to [this](https://merveilles.town/@whtrbt/102878830215381601) conversation, if this is indeed valid indental, then the nested parsing isn't working correctly in the wiki.

<img width="424" alt="Screenshot 2019-09-30 at 08 52 41" src="https://user-images.githubusercontent.com/13974112/65855778-1cbc9f80-e360-11e9-9473-8be61896af47.png">

**Comment by neauoire** [comment]
It's not a valid indental, a value is either a dict or an array.
In `A nested header` you've mixing key-val with a list of items.

**Comment by ckipp01** [comment]
Actually going to open this back up.

Just nested lists seems to parse correctly, however, they aren't displayed correctly in the wiki. See the below example.

<img width="811" alt="Screenshot 2019-09-30 at 16 13 56" src="https://user-images.githubusercontent.com/13974112/65886893-755e5d80-e39d-11e9-808e-ae1258d716b6.png">
