### ISSUE TITLE
https://wichniow.ski/ is a 404

### ISSUE THREAD

**Issue by ckipp01** [XXIIVV/Webring#329]
Does anyone know the owner of this site? We don't have any contact info, and from what I can get tell via git blame, the person no longer has a GitHub account. The site has been down for a couple of weeks now.

I'll leave this up for a week, and if there is no response, I'll remove it from the ring.

**Comment by kodedninja** [comment]
I think if you've been observing that it's been down, just remove it. There always a chance to add it back and this somehow enforces some activity within the ring too.

**Comment by joshavanier** [comment]
It's @wichniowski
