### ISSUE TITLE
Site with missing webring logo

### ISSUE THREAD

**Issue by aadilayub** [XXIIVV/Webring#348]
I was hopping webring sites and landed on [this one](http://luminghao.com/) which has no webring logo or link.

**Comment by ilyakooo0** [comment]
There actually is a link

![CC2DBDDE-9851-41B8-BD29-B4D13161E933](https://user-images.githubusercontent.com/6209627/70386578-eaa46b00-19aa-11ea-8a40-249f1ee9d506.jpeg)

**Comment by ilyakooo0** [comment]
It’s not obvious — I didn’t initially understand how I got there. You have to click on “ luming hao is a defender of qr codes.”

**Comment by aadilayub** [comment]
oh wow, that is confusing but also kind of cool. 
I'll be closing this issue and then.
