### ISSUE TITLE
s-ol.nu formatting broken

### ISSUE THREAD

**Issue by s-ol** [XXIIVV/webring#384]
**Name of the site:** `mmm.s-ol.nu`

The site is displayed as `mmm.s-ol` in the index, when it should rather be `mmm.s-ol.nu` or `s-ol.nu`.
In general as the "index" URL I prefer `s-ol.nu` (without subdomain), which will redirect to `https://mmm.s-ol.nu`, but I understand if you want to avoid the redirect.

**Comment by neauoire** [comment]
The url wasn't broken, the display name didn't show the extension `.nu`.
I've changed it to `<a href="https://mmm.s-ol.nu">s-ol.nu</a>`, but the link still points to `mmm`, that's how you made the PR.

**Comment by s-ol** [comment]
Yeah that's what I meant, the "broken link" label was just the closest of the template issues. Thanks :)
