### ISSUE TITLE
https for the icon

### ISSUE THREAD

**Issue by rh0** [XXIIVV/webring#4]
Can webring.xxiivv.com load https without a self signed cert.  Trying to load the icon via http will run up against CSP's and not be loaded on https sites.

**Comment by neauoire** [comment]
I have to wait for Github pages to validate this url.
In the meantime, just host the svg locally.

**Comment by rh0** [comment]
Bueno, I'll pull the svg down in the meantime.

**Comment by s-ol** [comment]
@neauoire I had a problem with github where it wouldn't fix the cert after a day even. When I removed the custom domain setting and just put it back it worked immediately - maybe try that.

**Comment by neauoire** [comment]
thanks I'll give it a shot

**Comment by 0101solar** [comment]
I've hosted the icons meanwhile the GitHub Pages gives @neauoire a certificate.
https://webring.1010.voyage

**Comment by neauoire** [comment]
Github won't validate the url :(

**Comment by xsv1010** [comment]
Oh, no. :(
I'll keep hosting the icons though :)

**Comment by xsv1010** [comment]
(and actually host them since it's down? )

**Comment by neauoire** [comment]
Nevermind, fixed :)
