### ISSUE TITLE
Indicate visited links

### ISSUE THREAD

**Issue by AdamSzakal** [XXIIVV/webring#405]
Personally, I'm having a hard time trying to keep track on which of the links I've visited. 

Adding some styling for the `:visited` pseudo class would do wonders for browseability (that's not a real word), especially as the list has grown to over a hundred(!!) links.

**Comment by neauoire** [comment]
It's been on my TODO for a little while but I haven't found a way to do this properly, the `visited` pseudoclass allows very little styling and I don't want to colorize the links, any suggestion?

**Comment by AdamSzakal** [comment]
Read up on it, and wow: the styling has become more limited than I thought. I'm guessing not colorizing is a stylistic choice, and I'm not sure what you would've done would there be no limitations to `:visited` (strikethrough being the most obvious non-colorized option) – but I found a list of hacks over at [CSS Tricks](https://css-tricks.com/almanac/selectors/v/visited/#article-header-id-2)

**Comment by Arty2** [comment]
One solution to avoid coloring or underlining the links would be to add a very discrete character on a pseudoelement, such as:

```
body a:visited::after { content: '}’ '; }
```

or (perhaps more visible):

```
body a:visited::before{ content: '`{'; }
```

**Comment by Arty2** [comment]
Correcting myself, apparently history jacking was more elaborate than I'd remember…

Illustrating one valid approach here, to set the curly brackets to the background color:

![image](https://user-images.githubusercontent.com/3519269/90387932-b7fd5700-e08f-11ea-9f62-c4d2c1480ce0.png)

For the light (default) theme:
```
body li a:visited:before { color: var(--color-beta);}
body li a:visited:after { color: var(--color-beta);}
```

**Comment by aadilayub** [comment]
@neauoire you could change the visited links to a more muted gray. It would still be monochrome.

**Comment by neauoire** [comment]
Oh @Arty2 I didn't think history would work with before and after!! I'll implement it.

**Comment by neauoire** [comment]
@aadilayub no, only black and white. :)

**Comment by neauoire** [comment]
Same issue with, in Firefox:
```
body a:visited:before { color:red; } 
```
