### ISSUE TITLE
https://webring.xxiivv.com/#random no longer redirects to a random page in the ring

### ISSUE THREAD

**Issue by quite** [XXIIVV/webring#409]
Or is that intentional?

**Comment by icco** [comment]
I'm also seeing this.

**Comment by aadilayub** [comment]
@quite It is intentional I think. @neauoire recently removed all JS from the site. I asked them about the #random feature and they said they'll see what they can do.

**Comment by resynth1943** [comment]
Unless you do some server-side magic, and change the thing to `?random`, I don't really see how this is possible without client-side magic

**Comment by aadilayub** [comment]
As an aside, I made a [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/merveilles-webring-surfer/) that basically does the same thing as webring.xxiivv.com/#random. So if anyone wants they can use that instead.

**Comment by jamesgoca** [comment]
I have created a simple Python script that returns a random link from the XXIIVV webring and opens it in a web browser. Anyone interested can use it. The repository is available at [jamesgoca/xxiivv-random](https://github.com/jamesgoca/xxiivv-random). The inspiration was @aadilayub's Firefox extension.

There's so many good links available on XXIIVV. I understand the decision to remove #random if it means including JS.

**Comment by cblgh** [comment]
@quite with the advent of the [webring search engine](https://github.com/cblgh/lieu) i made, there's now a random option again :)
https://lieu.cblgh.org/random

devine recently patched the webring website, adding a link to it at the bottom, as well.

**Comment by neauoire** [comment]
yup! will close this now :)
