### ISSUE TITLE
Directory redirects to random page

### ISSUE THREAD

**Issue by 0101solar** [XXIIVV/webring#42]

**Comment by neauoire** [comment]
huh?
You get redirected if you go to this page?
http://webring.xxiivv.com

**Comment by 0101solar** [comment]
Clicking the directory link in http://webring.xxiivv.com/#random redirects me back to http://webring.xxiivv.com/#random

**Comment by 0101solar** [comment]
Also, found an entry that said `Redirecting to undefined...`

**Comment by neauoire** [comment]
that's so weird.
Are you using IE?

<img width="370" alt="screen shot 2018-05-19 at 12 17 50 pm" src="https://user-images.githubusercontent.com/1455726/40262796-b6411d10-5b5e-11e8-8d96-f8af4fa60f3c.png">

**Comment by 0101solar** [comment]
Nope, I'm using Safari in macOS HS

**Comment by neauoire** [comment]
Do you get an error in the console?

**Comment by neauoire** [comment]
Just saw the `undefined`, okay, something's up.

**Comment by 0101solar** [comment]
Nope.

**Comment by 0101solar** [comment]
I submitted a pull request for the `undefined` bug

**Comment by neauoire** [comment]
merged, thanks Noah

**Comment by neauoire** [comment]
I forgot, still have to try and replicate the #random redirect issue.

**Comment by 0101solar** [comment]
The line setting the HTML for the random page had the Directory link doing `window.location.reload()`and no href at all.

https://github.com/XXIIVV/webring/pull/44

**Comment by 0101solar** [comment]
oh just noticed you already merged it
:P

**Comment by neauoire** [comment]
I figured that an empty href would remove the hash from the url.
That's probably better!
