### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nobodyindustries** [XXIIVV/webring#562]
https://letters.vexingworkshop.com is broken (No. 63)

**Comment by neauoire** [comment]
I think that's @coyote240 website

**Comment by coyote240** [comment]
Yes, that's me, sorry. Broke my cluster, haven't gotten back to fix it. If I haven't been kicked off yet, look for a fix soon. If I have, look for me to resubmit.

**Comment by coyote240** [comment]
Site is back up. I believe this issue can be closed.

**Comment by neauoire** [comment]
perfect :)
