### ISSUE TITLE
cblgh.org and the search @ lieu.cblgh.org is down

### ISSUE THREAD

**Issue by mrshll** [XXIIVV/webring#614]
@cblgh FYI - wanted to use the search today (I haven't since I first saw it -- it's super cool!) but wasn't able to access it. I tried to check your site for contact info and it also seemed down.

cblgh.org directly gets connection refused. The search subdomain gets nginx's hello world.

**Comment by cblgh** [comment]
@mrshll yes, i'll be bringing everything up this week. sorry for the interruption; had to research, buy and set up a new server (hardware & os maintenance is not my fav ahah). feel free to [chip in](https://github.com/sponsors/cblgh) a buckerino or two if you find my output useful or inspiring :)

**Comment by mrshll** [comment]
I do find your work interesting useful, and have been following cabal as well. I'm now "one peer, supporting another" ✌️

I'm sure you've got it, but if I can help at all, lmk.

**Comment by cblgh** [comment]
I appreciate that a bunch, thank you @mrshll! :black_heart: I'll be sure to ping you later this week once everything is up & running again :blush:

**Comment by cblgh** [comment]
@mrshll https://cblgh.org && [lieu](https://lieu.cblgh.org) are now operational again!

**Comment by cblgh** [comment]
@neauoire this can be closed now :)

**Comment by mrshll** [comment]
Hip hip!
