### ISSUE TITLE
[broken link] 166 - voidjumper.glass

### ISSUE THREAD

**Issue by GiacintoCarlucci** [XXIIVV/webring#638]
Exploring the page i was not able to open this link: **host unreachable**

@neauoire hope this is useful

**Comment by neauoire** [comment]
cc @voidjvmper

**Comment by voidjvmper** [comment]
Apologies for the (long) delay. Issue seems to be on my side. Site should be live on the net again. Cheers.

**Comment by neauoire** [comment]
yup, works again :)
