### ISSUE TITLE
21. jmandel.xyz domain expired

### ISSUE THREAD

**Issue by JakeMBauer** [XXIIVV/webring#645]
**Name of the site:** jmandel.xyz

The previous owner of the domain seems to have not renewed it and it is now owned by a domain reseller. Below is a screenshot of the error encountered when trying to visit the site:

<img width="631" alt="Screen Shot 2021-12-01 at 21 03 47" src="https://user-images.githubusercontent.com/32146222/144344053-85d54065-d96c-45f4-9b43-4b58a437dc56.png">

**Comment by neauoire** [comment]
Thanks for the tip :) removed
