### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by zioibi** [XXIIVV/webring#662]
I just took a trip around the webring, and I had trouble retrieving the following sites: 

```
45. iko.soy
52. xuv.be
62. Teknari
88. royniang.com
144. 01
164. voidjumper.glass
```

**Comment by neauoire** [comment]
@teknari @xuv @voidjvmper

**Comment by neauoire** [comment]
Removed royniang from the ring

**Comment by xuv** [comment]
On my side. This is an anomaly. My best guess is something to do with the hosting provider. Thanks for the notification. Will investigate and report back here.

**Comment by xuv** [comment]
It's fixed on my side. Thanks again for raising the issue.

**Comment by teknari** [comment]
Devine,

I guess you can remove teknari.com from the list for now. If/when I get it back up I can add it back again.

Thanks and I hope all is well!
Brent

------- Original Message -------

**Comment by neauoire** [comment]
@teknari lemme know if you do :)

**Comment by tosatur** [comment]
I contacted the owners of voidjumper.glass and xuv.be, will close this issue after they both respond

The rest of the sites are either fixed or already removed

**Comment by neauoire** [comment]
Updated the dead ones, thanks :)
