### ISSUE TITLE
of lost links & missing rings

### ISSUE THREAD

**Issue by 87F** [XXIIVV/webring#710]
I've been crawling through the webring sites and found a few broken links and a site that no longer seems to link back to the webring. most of the broken links were already raised in previous issues but I'll just list them here:
- .008 https://anxl.faith/
- .034 https://underscorediscovery.ca/
- .071 https://gueorgui.net/
- .140 https://0l.wtf/
- .164 https://dyslexic.ink/

site with no webring links:
- .108 https://www.marginchronicles.com/site/essays/-feed.html

**Comment by neauoire** [comment]
Thanks removed :)
