### ISSUE TITLE
Break links

### ISSUE THREAD

**Issue by matheplica** [XXIIVV/webring#725]
Hi, links 3-5-8-23-34-42-64-71-79-111-114-122-140-155-164 are broken.

**Comment by neauoire** [comment]
Thanks! I will go through the list and contact the owners :)

**Comment by HoangTuan110** [comment]
I have checked all of the links.

The links 3, 23, 34, 42 is working well. Every other link isn't working.

**Comment by neauoire** [comment]
Removed dead ones, thanks :)
