### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by plknkl** [XXIIVV/webring#745]
Hello!

I run a small script to check the dead links, and found some:

https://anxl.faith/   ERR_CONNECTION_REFUSED
http://controls.ee/   ERR_CONNECTION_REFUSED
https://underscorediscovery.ca/   ERR_CONNECTION_REFUSED
http://www.miha-co.ca/   ERR_CONNECTION_REFUSED
https://gueorgui.net/   ERR_CONNECTION_REFUSED
https://dotcomboom.somnolescent.net/   ERR_CONNECTION_REFUSED
https://solquemal.com/   ERR_CONNECTION_REFUSED
https://garden.tymon-zaniewski.xyz/   ERR_CONNECTION_REFUSED
https://0l.wtf/   ERR_CONNECTION_REFUSED
https://oppen.digital/   ERR_CONNECTION_REFUSED
https://dyslexic.ink/   PAGE_NOT_FOUND

**Comment by neauoire** [comment]
Thanks, I've given the sites 2 months to come back online, and I've removed those which did not :)
