### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by shrik3** [XXIIVV/webring#892]
https://www.materialfuture.net

<del>https://tosatur.com</del>

**Comment by tosatur** [comment]
Hi, tosatur.com is my website, it should be up and running now, sorry about that!

**Comment by tosatur** [comment]
https://www.materialfuture.net/ seems to be an Indonesian gambling related site now?

Not sure what happened but it is definitely different from what it was before!
https://web.archive.org/web/20240106004311/https://materialfuture.net/

**Comment by neauoire** [comment]
Removed thanks :)
