### ISSUE TITLE
Broken link: Pachapunk.space

### ISSUE THREAD

**Issue by jenkemisreal** [XXIIVV/webring#936]
Pachapunk.space redirects to a godaddy page to buy the domain name. 

https://www.godaddy.com/forsale/pachapunk.space?utm_source=TDFS_BINNS&utm_medium=parkedpages&utm_campaign=x_corp_tdfs-binns_base&traffic_type=TDFS_BINNS&traffic_id=binns&

**Comment by neauoire** [comment]
Removed it, thanks for the head's up.
