### ISSUE TITLE
More dead websites

### ISSUE THREAD

**Issue by gytdau** [XXIIVV/Webring#95]
Here they are:
- https://cblgh.org/
- https://xarene.la/
- https://ellugar.co/
- https://monochromatic.co/

Although maybe it's not safe to assume they're dead forever, they could be hosted on tiny Raspberry Pis that their owner accidentally unplugged. It's a nice thought, having servers that aren't constantly up and managed in data centers. Like business hours for websites.

But that's unlikely. I think they should be removed.

**Comment by neauoire** [comment]
@afk-mcz 's ellugar works for me.

@xarene DEAD
@MoreThanLuck DEAD
@cblgh DEAD

**Comment by gytdau** [comment]
You're right, that does work. Maybe I just visited it at a bad time.

**Comment by neauoire** [comment]
I'll see if there's replies here, otherwise I will move them out of the list :)

**Comment by MoreThanLuck** [comment]
Whoops! I'm https://mnchrm.co now. I'll revise this as soon as I'm able.

**Comment by cblgh** [comment]
I'm still in the process of packing up after the move, but cblgh.org should
be up again this week. :)
